---
# tasks file for ntp

- name: Ensure NTP (for time synchronization) is installed.
  yum: name=ntp state=installed
- name: set timezone to Europe/Rome
  timezone: name=Europe/Rome
- name: Ensure NTP is running.
  service: name=ntpd state=started enabled=yes

